### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by Luowenjin826** [astrazeneca-cgr-publications/mantis-ml-release-2.0#1]
Hey!I got the 403 Forbidden error after running mantisml2 -d "diabetes mellitus" -o mantisml_diabetes_out -m sgcn in ubuntu20.04:
  File "/home/luo_wenjin/mambaforge/envs/mantis_ml_2/lib/python3.8/site-packages/download/download.py", line 119, in download
    _fetch_file(
  File "/home/luo_wenjin/mambaforge/envs/mantis_ml_2/lib/python3.8/site-packages/download/download.py", line 277, in _fetch_file
    raise RuntimeError(
RuntimeError: Error while fetching file https://ndownloader.figshare.com/files/12551759. Dataset fetching aborted.
Error: HTTP Error 403: Forbidden

Then I run wget https://ndownloader.figshare.com/files/12551759:
Connecting to ndownloader.figshare.com (ndownloader.figshare.com)|52.209.182.24|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden

But I successfully downloaded "https://ndownloader.figshare.com/files/12551759" in Firefox browser.

May I ask how to fix it?
Thanks!

**Comment by ghost** [comment]
Sounds like a firewall issue (potentially!)

Have you tried the steps at the bottom of the README? Basically, the code expects the file downloaded from figshare to be placed at `mantis_ml/data/bioword2vec_embeddings/bio_embedding_intrinsic` (i.e. the name of the file is bio_embedding_intrinsic) and is placed in mantis_ml/data/bioword2vec_embeddings.

Hope this helps!

**Comment by Luowenjin826** [comment]
It does work. Thank you!
